apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: devops-toolkit
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 100
      containers:
      - image: vfarcic/devops-toolkit-series
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
